<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UsuariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ============================================================
        // 1️⃣ LIMPIAR TABLA (para tener IDs exactos)
        // ============================================================
        $this->command->info('🗑️  Eliminando todos los usuarios existentes...');
        
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('usuarios')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $this->command->info('✅ Tabla usuarios limpiada correctamente.');
        
        // ============================================================
        // 2️⃣ DEFINIR LOS USUARIOS CON LA ESTRUCTURA DEL MODELO
        // ============================================================
        $usuarios = [
            [
                'id_usuario' => 1,
                'nombre_completo' => 'JESUS DIAZ CONTRERAS',
                'nombre_usuario' => 'JESUS',
                'email' => 'jesusdiazcontreras@gmail.com',
                'password_hash' => Hash::make('JEDICON'),
                'telefono' => '7351478868',
                'tipo_usuario' => 'SUPERUSUARIO',
                'activo' => true,
                'fecha_creacion' => Carbon::now(),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 2,
                'nombre_completo' => 'KAREN GOMEZ DOMINGUEZ',
                'nombre_usuario' => 'KAREN',
                'email' => 'karen.gomez@csa.com',
                'password_hash' => Hash::make('KAREN2021'),
                'telefono' => '7352146160',
                'tipo_usuario' => 'SUPERUSUARIO',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-10-16 10:23:30'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-10-16 10:23:30'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 3,
                'nombre_completo' => 'JAQUELIN RAMOS ALATOMA',
                'nombre_usuario' => 'JAQUELIN',
                'email' => 'asistente.contab07@gmail.com',
                'password_hash' => Hash::make('line07'),
                'telefono' => '7352391595',
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-11-03 10:22:34'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-03 10:22:34'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 4,
                'nombre_completo' => 'ANAYELI MEDINA ORTIZ',
                'nombre_usuario' => 'ANAYELI',
                'email' => 'medi18naye@gmail.com',
                'password_hash' => Hash::make('KAREN2021'),
                'telefono' => '7351067593',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-03 11:41:03'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-03 11:41:03'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 5,
                'nombre_completo' => 'ESTRELLA MORALES SANTANERO',
                'nombre_usuario' => 'ESTRELLA',
                'email' => 'estrellamoralessantanero@gmail.com',
                'password_hash' => Hash::make('29092002E'),
                'telefono' => '7352518549',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-11-03 12:18:22'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-03 12:18:22'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 6,
                'nombre_completo' => 'AISLIN DOMINGUEZ VAZQUEZ',
                'nombre_usuario' => 'AISLIN',
                'email' => 'adominguezvazquez291103@gmail.com',
                'password_hash' => Hash::make('AISLIN03'),
                'telefono' => '7352131303',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-03 12:23:51'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-03 12:23:51'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 7,
                'nombre_completo' => 'ELIZA PACHECO VELAZQUEZ',
                'nombre_usuario' => 'ELIZA',
                'email' => 'lab.csa2022@gmail.com',
                'password_hash' => Hash::make('PACHECO'),
                'telefono' => null,
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-11-13 14:28:46'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-13 14:28:46'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 8,
                'nombre_completo' => 'ROBERTO BRAYHAM LOPEZ PLIEGO',
                'nombre_usuario' => 'BRAYHAM',
                'email' => 'brayham_360@hotmail.com',
                'password_hash' => Hash::make('YUKITO735'),
                'telefono' => '7352599676',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-16 14:59:19'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-16 14:59:19'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 9,
                'nombre_completo' => 'ROSI LARIOS HERNANDEZ',
                'nombre_usuario' => 'LARIOS',
                'email' => 'rosilarioshernandez@gmail.com',
                'password_hash' => Hash::make('LARIOS'),
                'telefono' => '2431153478',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-18 09:54:52'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-18 09:54:52'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 10,
                'nombre_completo' => 'MARIA DEL ROSARIO AGUILAR LINARES',
                'nombre_usuario' => 'ROSARIO',
                'email' => 'rosario-1703@hotmail.com',
                'password_hash' => Hash::make('ROSARIO'),
                'telefono' => '7351266764',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-18 09:59:02'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-18 09:59:02'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 11,
                'nombre_completo' => 'DANIELA BARRETO ALCONEDO',
                'nombre_usuario' => 'DANIELA',
                'email' => 'daniela.barretoalconedo33@gmail.com',
                'password_hash' => Hash::make('DANIELA'),
                'telefono' => '7351597926',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-11-20 08:04:20'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-20 08:04:20'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 12,
                'nombre_completo' => 'BRYAN CASTELAN GARCIA',
                'nombre_usuario' => 'BRYAN',
                'email' => 'garcia_bryhan@hotmail.com',
                'password_hash' => Hash::make('11072001'),
                'telefono' => '7352039337',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2023-11-22 08:57:07'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-22 08:57:07'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 13,
                'nombre_completo' => 'SARAHI JHOSAFTH PACHECO TAPIA',
                'nombre_usuario' => 'SARA',
                'email' => 'sara@gmail.com',
                'password_hash' => Hash::make('123456'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2023-11-28 08:08:50'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2023-11-28 08:08:50'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 14,
                'nombre_completo' => 'SARAY LINARES MEDINA',
                'nombre_usuario' => 'SARAY',
                'email' => 'sistemagc.csa@gmail.com',
                'password_hash' => Hash::make('LINARES'),
                'telefono' => '6677913804',
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2024-01-22 10:25:00'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-01-22 10:25:00'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 15,
                'nombre_completo' => 'PATRICIA VARA VARGAS',
                'nombre_usuario' => 'PATRICIA',
                'email' => 'auditorclinica@gmail.com',
                'password_hash' => Hash::make('PATRICIA'),
                'telefono' => '7351492504',
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2024-01-22 10:27:03'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-01-22 10:27:03'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 16,
                'nombre_completo' => 'VICTOR URIEL GENIS DIAZ',
                'nombre_usuario' => 'VICTOR',
                'email' => 'victor.genis@csa.com',
                'password_hash' => Hash::make('victor123'),
                'telefono' => '7351264920',
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2024-01-31 10:43:31'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-01-31 10:43:31'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 17,
                'nombre_completo' => 'ITZEL RAMIREZ CONTRERAS',
                'nombre_usuario' => 'ITZEL',
                'email' => 'itezel.ramirez@gmail.com',
                'password_hash' => Hash::make('ITZEL123'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2024-03-01 12:07:56'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-03-01 12:07:56'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 18,
                'nombre_completo' => 'ROCIO CUATE PACHECO',
                'nombre_usuario' => 'ROCIO',
                'email' => 'rcuatepacheco@gmail.com',
                'password_hash' => Hash::make('PACHECO'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2024-04-01 12:52:50'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-04-01 12:52:50'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 19,
                'nombre_completo' => 'EDUARDO SEBASTIAN CRUZTITLA VILLANUEVA',
                'nombre_usuario' => 'EDUARDO',
                'email' => 's.antonioclinica@hotmail.com',
                'password_hash' => Hash::make('EDUARDO01'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2024-07-01 12:00:23'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-07-01 12:00:23'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 20,
                'nombre_completo' => 'SOFIA BARRETO ESPANA',
                'nombre_usuario' => 'AUDITOR',
                'email' => 'barretosofia086@gmail.com',
                'password_hash' => Hash::make('11SOOF'),
                'telefono' => '7351817402',
                'tipo_usuario' => 'ADMINISTRADOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2024-09-09 14:48:28'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-09-09 14:48:28'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 21,
                'nombre_completo' => 'SERGIO ENRIQUE RUZ PLIEGO',
                'nombre_usuario' => 'ENRRIQUE',
                'email' => 'ruizkicke@gmail.com',
                'password_hash' => Hash::make('RUPS990513'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => false,
                'fecha_creacion' => Carbon::parse('2024-10-03 09:06:01'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2024-10-03 09:06:01'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 22,
                'nombre_completo' => 'LUZ DENISSE VARGAS SEVERIANO',
                'nombre_usuario' => 'DENISSE',
                'email' => 'luz@gmail.com',
                'password_hash' => Hash::make('LUZ1305.,'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-01-04 08:53:12'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-01-04 08:53:12'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 23,
                'nombre_completo' => 'LITZI RAMOS MORAN',
                'nombre_usuario' => 'LITZI',
                'email' => 'rplitziramos@gmail.com',
                'password_hash' => Hash::make('LITZI123'),
                'telefono' => '2431552071',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-03-16 11:48:12'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-03-16 11:48:12'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 24,
                'nombre_completo' => 'GABRIEL SANTIAGO ELIZARRARAS FONSECA',
                'nombre_usuario' => 'GABRIEL',
                'email' => 'elizarraras_gabriel@outlook.com',
                'password_hash' => Hash::make('Arisman.75'),
                'telefono' => null,
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-09-02 11:14:50'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-09-02 11:14:50'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 25,
                'nombre_completo' => 'NADIA KAREN GARCIA VALERO',
                'nombre_usuario' => 'NADIA',
                'email' => 'nadia.garcia@csa.com',
                'password_hash' => Hash::make('NADIA123'),
                'telefono' => '2217926700',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-09-19 09:11:02'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-09-19 09:11:02'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 26,
                'nombre_completo' => 'DIEGO PERALTA LUNA',
                'nombre_usuario' => 'DIEGO',
                'email' => 'diego.peralta@csa.com',
                'password_hash' => Hash::make('110302'),
                'telefono' => '7351044525',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-11-15 09:20:32'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-11-15 09:20:32'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 27,
                'nombre_completo' => 'ALDAIR JESUS RAMIREZ TAJONAR',
                'nombre_usuario' => 'ALDAIR',
                'email' => 'supervisorauditorcsa@gmail.com',
                'password_hash' => Hash::make('ALDAIR'),
                'telefono' => '7299927721',
                'tipo_usuario' => 'ADMINISTRADOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2025-11-21 11:38:59'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2025-11-21 11:38:59'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 28,
                'nombre_completo' => 'SALMA GUERRERO AMACENDE',
                'nombre_usuario' => 'SALMA',
                'email' => 'salma.guerrero@csa.com',
                'password_hash' => Hash::make('SALMA3'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-01-28 13:34:19'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-01-28 13:34:19'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 29,
                'nombre_completo' => 'MICHELIE MEJIA VENACIO',
                'nombre_usuario' => 'MICHELIE',
                'email' => 'michelie.mejia@csa.com',
                'password_hash' => Hash::make('MICHELIE'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-02-03 09:49:08'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-02-03 09:49:08'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 30,
                'nombre_completo' => 'SARAHI BELTRAN VINESAS',
                'nombre_usuario' => 'SARAHI',
                'email' => 'sarahi.beltran@csa.com',
                'password_hash' => Hash::make('090223'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-02-26 16:43:05'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-02-26 16:43:05'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 31,
                'nombre_completo' => 'ALESSHANDRA MAYERLY TERRAZASS VARGAS',
                'nombre_usuario' => 'VARGAS',
                'email' => 'aleodontotepalcingo@icloud.com',
                'password_hash' => Hash::make('ALESSHANDRA'),
                'telefono' => null,
                'tipo_usuario' => 'CAPTURISTA',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-02-27 11:04:58'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-02-27 11:04:58'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 32,
                'nombre_completo' => 'GLADIZ ARISBETH ARREDONDO GARCIA',
                'nombre_usuario' => 'GLADIZ',
                'email' => 'gladiz.arredondo@csa.com',
                'password_hash' => Hash::make('GLADIZ'),
                'telefono' => '7352146160',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-02-27 15:53:04'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-02-27 15:53:04'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 33,
                'nombre_completo' => 'ANAYELI BARRENO PACHECO',
                'nombre_usuario' => 'BARRENO',
                'email' => 'barrenoanayeli@gmail.com',
                'password_hash' => Hash::make('CIELOBP'),
                'telefono' => '7351066173',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-03-03 10:26:39'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-03-03 10:26:39'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 34,
                'nombre_completo' => 'JONATHAN TAPIA SANTIAGO',
                'nombre_usuario' => 'SANTIAGO',
                'email' => 'jonathan.tapia@csa.com',
                'password_hash' => Hash::make('SANTIAGO'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-03-16 10:10:44'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-03-16 10:10:44'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 35,
                'nombre_completo' => 'JORGE YAEL RAMIREZ ZAPATA',
                'nombre_usuario' => 'YAEL',
                'email' => 'jorge.ramirez@csa.com',
                'password_hash' => Hash::make('240400'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-05-30 16:11:48'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-05-30 16:11:48'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 36,
                'nombre_completo' => 'MAYELI TAPIA JIMENEZ',
                'nombre_usuario' => 'MAYELI',
                'email' => 'mayeli.tapia@csa.com',
                'password_hash' => Hash::make('MAYELI'),
                'telefono' => null,
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-06-05 12:31:13'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-06-05 12:31:13'),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_usuario' => 37,
                'nombre_completo' => 'TIRZA GENIS NAJERA',
                'nombre_usuario' => 'TIRZA',
                'email' => 'tirza_genis_240900@hotmail.com',
                'password_hash' => Hash::make('Tirza2409'),
                'telefono' => '7351004139',
                'tipo_usuario' => 'LECTOR',
                'activo' => true,
                'fecha_creacion' => Carbon::parse('2026-07-21 14:12:46'),
                'ultimo_acceso' => null,
                'remember_token' => null,
                'created_at' => Carbon::parse('2026-07-21 14:12:46'),
                'updated_at' => Carbon::now(),
            ],
        ];

        // ============================================================
        // 3️⃣ INSERTAR TODOS LOS USUARIOS
        // ============================================================
        foreach ($usuarios as $usuario) {
            DB::table('usuarios')->insert($usuario);
            $this->command->info("✅ Usuario ID {$usuario['id_usuario']} - {$usuario['nombre_usuario']} insertado correctamente.");
        }

        // ============================================================
        // 4️⃣ REINICIAR AUTO_INCREMENT PARA QUE EL PRÓXIMO SEA 38
        // ============================================================
        DB::statement('ALTER TABLE usuarios AUTO_INCREMENT = 38;');

        $this->command->info("🎉 ¡Seeder ejecutado exitosamente!");
        $this->command->info("📊 Se insertaron 37 usuarios con IDs del 1 al 37.");
        $this->command->info("🔢 El próximo ID será 38.");
    }
}